### PR TITLE
Add: SwapTokensAndStakeDev

### PR DESCRIPTION
**Pull request by KukretiShubham**
This contract would
- enable the use of ANY token for purchasing club memberships through Uniswap V3 pool.
- support purchase via native tokens
- custom path as an argument that can be followed for executing a swap

### CODE REVIEW

**Review by aggre — COMMENTED** [review]
These are significant changes!
I have simple change proposals that, I feel, are only necessary for **SwapTokensAndStakeDev**:
- Can all `swapUsdcAndStakeDev` overloads have an explicit destination like `address _to`? Because Crossmint needs to know whom to drop the NFT on.  If the user doesn't go through Crossmint, just input the user own EOA there.
- Can `Amounts` have an address indicating the input token, eg `address token`? It could be 0 address when the native token is used.

**Comment by KukretiShubham** [comment]
> * Can all `swapUsdcAndStakeDev` overloads have an explicit destination like `address _to`? Because Crossmint needs to know whom to drop the NFT on.  If the user doesn't go through Crossmint, just input the user own EOA there.

Do you mean instead of `msg.sender` [here](https://github.com/dev-protocol/eth-swap-and-stake/blob/swap-token/contracts/SwapTokensAndStakeDev.sol#L300), we pass an address as an argument?

> * Can `Amounts` have an address indicating the input token, eg `address token`? It could be 0 address when the native token is used.

Sure, I can

**Comment by aggre** [comment]
> Do you mean instead of `msg.sender` [here](https://github.com/dev-protocol/eth-swap-and-stake/blob/swap-token/contracts/SwapTokensAndStakeDev.sol#L300), we pass an address as an argument?

@KukretiShubham Yeah, that's I meant. And this is just my opinion, but I think we can add `_to` to all `swapUsdcAndStakeDev` functions because to avoid adding too many overloads.

**Comment by KukretiShubham** [comment]
I have added address  `_to` . This one is implemented in a separate contract `SwapTokensAndStake`. Do we need `SwapUsdcAndStake` contract anymore?

**Review by aggre — APPROVED** [review]

**Comment by aggre** [comment]
`SwapTokensAndStake` basically covers the specification of `SwapUsdcAndStake`, so we will use `SwapTokensAndStake` as the main contract.

**Pull request merged**
